bot:
  name: SweetBot
  token: 6835294052:AAEu9llAyx5wzaDpZlt88PQ4MjCkQoCBmSs
  owner:
    1: 1631579869
    2: 5134470151

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.8.206:5432/paspay_sweet_bot?prepareTreshold=0
    username: paspay_sweet_bot
    password: A2!@!d3d32@
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
aws:
  s3:
    bucket: paspay-test
  upload-file:
    format: .xlsx
s3:
  url: https://paspay-test.archive.pscloud.io/report.txt
grpc:
  client:
    fileworker-grpc-server: # change to paspay-fileworker ip address
      address: static://192.168.8.184:30121
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext