bot:
  name: SweetBot
  token: 6835294052:AAEu9llAyx5wzaDpZlt88PQ4MjCkQoCBmSs
  owner:
    1: 1631579869

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.8.206:5432/paspay_sweet_bot?prepareTreshold=0
    username: paspay_sweet_bot
    password: A2!@!d3d32@
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
