bot:
  name: SweetBot
  token: 6835294052:AAEu9llAyx5wzaDpZlt88PQ4MjCkQoCBmSs
  owner:
    - 1631579869

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/paspay_acquiring_service?prepareTreshold=0
    username: paspay_acquiring_service
    password: q12@1weq3
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
