replicaCount: 1

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0

#image:
#  name: nginx:1.11
#  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: nexus-reg

nameOverride: paspay-sweet-bot-service
fullnameOverride: paspay-sweet-bot-service

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30117
env:
  open: []
  secret: []

vault:
  enabled: false

ingress:
  enabled: false
  annotations: 
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: example.kz
      paths:
        - /
  tls:
    - secretName: chart-example-tls
      hosts:
        - example.kz

resources:
  limits:
    cpu: 350m
    memory: 356Mi
  requests:
    cpu: 250m
    memory: 256Mi

extraVolumeMounts: []

extraVolumes: []

nodeSelector: []

tolerations: []

affinity: {}

cronjobs: []
